# Generated by Django 4.2.18 on 2026-07-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='student@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
